---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: xenial64
    box: ubuntu/xenial64
    memory: 2048
    cpus: 1
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8080"
      - "vm.network 'private_network', ip: '10.10.10.18'"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--cpuexecutioncap', '80']"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
